export const ERROR_CODES = [
  'AUTH_EMAIL_ALREADY_EXISTS',
  'AUTH_INVALID_CREDENTIALS',
  'AUTH_INVALID_TOKEN',
  'AUTH_REFRESH_REUSED',
  'AUTH_REFRESH_REVOKED',
  'AUTH_RESET_TOKEN_INVALID',
  'RESOURCE_NOT_FOUND',
  'VALIDATION_FAILED',
  'PAGINATION_INVALID_CURSOR',
  'IDEMPOTENCY_KEY_REQUIRED',
  'IDEMPOTENCY_KEY_REUSED',
  'TRANSACTION_INVALID_INSTALLMENTS',
  'TRANSACTION_INVALID_PAYMENT_METHOD',
  'TRANSACTION_INVALID_SCOPE',
  'FINANCIAL_RELATION_INVALID',
  'ACCOUNT_LAST_ACTIVE',
  'ACCOUNT_HAS_ACTIVE_CARDS',
  'ACCOUNT_HAS_ACTIVE_RECURRENCES',
  'CREDIT_CARD_HAS_ACTIVE_RECURRENCES',
  'INTERNAL_ERROR',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
